[global]
pid = /home/container/tmp/php-fpm.pid
error_log = /home/container/php-fpm.log
log_level = notice

; SÉCURITÉ & STABILITÉ
; Limite le nombre total de processus pour éviter l'épuisement de la RAM du container
process.max = 64

; Indispensable pour Pterodactyl/Docker : le processus doit rester au premier plan
daemonize = no

; Augmentation de la limite des descripteurs de fichiers
rlimit_files = 4096

;;;;;;;;;;;;;;;;;;;;;;;;
; Définitions des Pools ;
;;;;;;;;;;;;;;;;;;;;;;;;

; On inclut la configuration du pool (souvent www.conf)
include=/home/container/php-fpm/fpm.pool.d/*.conf